version: "3"
services:
  pgdb:
    container_name: postgres
    image: postgres
    env_file: ./.env
    ports:
      - "5432:5432"
  nest:
    container_name: nest
    build: .
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      - pgdb